name: Feature Request
description: Suggest an idea/feature
title: "feat: "
labels:
  - enhancement
  - triage
body:
  - type: markdown
    attributes:
      value: |
        Thanks for having interest in improving this project!
  - type: textarea
    id: suggested-idea
    attributes:
      label: What do you need?
      description: Also tell us, what is it needed for.
      placeholder: Tell us what you think!
    validations:
      required: true
  - type: textarea
    id: example
    attributes:
      label: Example
      description: Also tell us, how it's going to be used.
      placeholder: Give us an example
      render: typescript
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/extremejs/.github/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: "I agree to follow this project's Code of Conduct"
          required: true
